#build usa o docker file do diretório
#dockerfile é utilizado para preparar uma imagem individualmente
#docker-compose é utilizado para uma topologia de containers.

#PRIMEIRO CONTAINER
web:
  build: .

  links:
    - redis

  ports:
    - "3000"
    - "8000"

#CONTAINER REDIS
redis:
  image: redis:alpine
  volumes:
    #LOCAL ONDE OS DADOS VÃO SER GRAVADOS
    - /var/redis/data:/data



